name: fuckingnum
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read screens.more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read screens.more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter
  auto_size_text: ^2.0.2
  http: ^0.13.3
  firebase_auth: ^1.4.1
  scroll_bottom_navigation_bar: ^3.0.0
  flutter_multi_formatter: ^1.1.6
  flutter_rating_bar: ^3.0.1+1
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  fluttertoast: ^3.1.3
  carousel_pro: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  hexcolor: ^1.0.2
  image_picker: ^0.8.0+3
  story_view: ^0.12.3
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  dio: ^4.0.0
  bloc: ^0.8.0
  flutter_bloc: ^0.5.0
  meta: ^1.1.6
  equatable: ^0.1.6
  local_auth: ^1.1.6
  pattern_formatter: ^2.0.0
  dashed_circle: ^0.0.1
  url_launcher: ^6.0.6
  flutter_verification_code_input:
    git:
      url: git://github.com/tinylife-io/flutter_verification_code_input.git
      publish_to: none
  qr_code_scanner: ^0.0.13
  bouncing_widget: ^1.2.0

  flutter_keyboard_visibility: ^3.2.1
  social_media_widgets: ^1.0.0+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  characters: ^1.0.0
  share: ^0.6.4+5
  qr_flutter: ^3.2.0
  barcode_flutter: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icons/
    - images/

  # An image asset can refer to one or screens.more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
